# Generated by Django 3.0.2 on 2020-03-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackreview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
