# Generated by Django 3.0.2 on 2020-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='places_to_stay',
            field=models.IntegerField(default=0),
        ),
    ]
