# Generated by Django 3.0.2 on 2020-03-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_destination_places_to_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
    ]
