# Generated by Django 3.0.2 on 2020-03-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_destination_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
