# Generated by Django 3.0.2 on 2020-03-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='places_to_stay',
        ),
    ]
