# Generated by Django 3.0.2 on 2020-02-25 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('img', models.ImageField(upload_to='places')),
                ('price', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
                ('max_occupancy', models.IntegerField(default=0)),
                ('des_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Destination')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
