# Generated by Django 3.0.2 on 2020-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20200225_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
