# Generated by Django 3.0.2 on 2020-03-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_place_place_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='avg_rate',
            field=models.IntegerField(default=0),
        ),
    ]
